# Generated by Django 3.0.3 on 2020-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=5, null=True)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
        migrations.AlterModelTable(
            name='order',
            table='tb_order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='tb_product',
        ),
    ]
